# Sample public application.yml to be used by Spring Cloud Config Server

application:
    message: Configured by Spring Cloud Config Server for Microsoft Azure. That didnt work.. so adding actuator now
